/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteRuleta;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static paqueteRuleta.VPrincipal.ruleta;

/**
 *
 * @author Miguel
 */
public class VPreguntas extends javax.swing.JFrame {

    Pregunta seleccionada;
    DefaultListModel modeloPreguntas = new DefaultListModel();
    /**
     * Creates new form VPreguntas
     */
    public VPreguntas() {
        initComponents();
        listPreguntas.setModel(modeloPreguntas);
        for(Pregunta q : ruleta.baseDatos){
            modeloPreguntas.addElement(q);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listPreguntas = new javax.swing.JList();
        buttonBorrar = new javax.swing.JButton();
        buttonMostrarPanel = new javax.swing.JButton();
        buttonMostrarPanelRapido = new javax.swing.JButton();
        buttonMostrarPanelRapido1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Todas las preguntas.");

        listPreguntas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPreguntasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPreguntas);

        buttonBorrar.setBackground(new java.awt.Color(255, 0, 0));
        buttonBorrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonBorrar.setForeground(new java.awt.Color(255, 255, 255));
        buttonBorrar.setText("Borrar");
        buttonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarActionPerformed(evt);
            }
        });

        buttonMostrarPanel.setBackground(new java.awt.Color(0, 102, 204));
        buttonMostrarPanel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonMostrarPanel.setForeground(new java.awt.Color(255, 255, 0));
        buttonMostrarPanel.setText("Mostrar en panel");
        buttonMostrarPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarPanelActionPerformed(evt);
            }
        });

        buttonMostrarPanelRapido.setBackground(new java.awt.Color(0, 102, 204));
        buttonMostrarPanelRapido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonMostrarPanelRapido.setForeground(new java.awt.Color(255, 255, 0));
        buttonMostrarPanelRapido.setText("Mostrar en panel rápido");
        buttonMostrarPanelRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarPanelRapidoActionPerformed(evt);
            }
        });

        buttonMostrarPanelRapido1.setBackground(new java.awt.Color(0, 102, 204));
        buttonMostrarPanelRapido1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonMostrarPanelRapido1.setForeground(new java.awt.Color(255, 255, 0));
        buttonMostrarPanelRapido1.setText("Panel una palabra");
        buttonMostrarPanelRapido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarPanelRapido1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonMostrarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMostrarPanelRapido, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMostrarPanelRapido1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMostrarPanel)
                    .addComponent(buttonBorrar)
                    .addComponent(buttonMostrarPanelRapido)
                    .addComponent(buttonMostrarPanelRapido1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listPreguntasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPreguntasValueChanged
        int elementoSeleccionado = listPreguntas.getSelectedIndex();
        seleccionada = (Pregunta) modeloPreguntas.getElementAt(elementoSeleccionado);
    }//GEN-LAST:event_listPreguntasValueChanged

    private void buttonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarActionPerformed
        if(seleccionada != null){
            int n = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea eliminar esta pregunta?", "Eliminar panel", JOptionPane.WARNING_MESSAGE);
            if(n == JOptionPane.OK_OPTION){
                ruleta.baseDatos.remove(seleccionada);
                JOptionPane.showMessageDialog(null, "Pregunta eliminada con éxito.", "Panel eliminado", WIDTH);
                this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una pregunta para poder eliminarla", "Eliminar panel", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonBorrarActionPerformed

    private void buttonMostrarPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarPanelActionPerformed
        if(seleccionada != null){
            VPanel vp = new VPanel();
            vp.pregunta = seleccionada;
            vp.cambiaPanel();
            vp.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una pregunta para poder seleccionarla", "Seleccionar panel", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonMostrarPanelActionPerformed

    private void buttonMostrarPanelRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarPanelRapidoActionPerformed
        if(seleccionada != null){
            VPanel vp = new VPanel();
            vp.pregunta = seleccionada;
            vp.rapida = true;
            vp.cambiaPanel();
            vp.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una pregunta para poder seleccionarla", "Seleccionar panel", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonMostrarPanelRapidoActionPerformed

    private void buttonMostrarPanelRapido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarPanelRapido1ActionPerformed
        if(seleccionada != null){
            VPanel vp = new VPanel();
            vp.pregunta = seleccionada;
            vp.palabra = true;
            vp.cambiaPanel();
            vp.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una pregunta para poder seleccionarla", "Seleccionar panel", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonMostrarPanelRapido1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBorrar;
    private javax.swing.JButton buttonMostrarPanel;
    private javax.swing.JButton buttonMostrarPanelRapido;
    private javax.swing.JButton buttonMostrarPanelRapido1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listPreguntas;
    // End of variables declaration//GEN-END:variables
}
