/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteRuleta;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;


/**
 *
 * @author Miguel
 */
public class VPrincipal extends javax.swing.JFrame {

    public static Programa ruleta;
    /**
     * Creates new form VPrincipal
     */
    public VPrincipal(){
        initComponents();
        ruleta = new Programa();
        cargar();
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                for(Pregunta q : ruleta.baseDatos){
                    q.yaSeleccionada = false;
                }
                guardar();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfPanel1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPista = new javax.swing.JTextField();
        bNueva = new javax.swing.JButton();
        buttonPanelAzar = new javax.swing.JButton();
        tfPanel2 = new javax.swing.JTextField();
        tfPanel3 = new javax.swing.JTextField();
        tfPanel4 = new javax.swing.JTextField();
        tfError1 = new javax.swing.JTextField();
        tfError2 = new javax.swing.JTextField();
        tfError3 = new javax.swing.JTextField();
        tfError4 = new javax.swing.JTextField();
        buttonTodas = new javax.swing.JButton();
        buttonPanelRapido = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LA RULETA DE LA SUERTE");

        jLabel1.setText("Panel (ESCRIBIR EN MAYÚSCULAS):");

        jLabel2.setText("Pista:");

        bNueva.setText("Añadir");
        bNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevaActionPerformed(evt);
            }
        });

        buttonPanelAzar.setText("Ver Panel Al Azar");
        buttonPanelAzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanelAzarActionPerformed(evt);
            }
        });

        tfError1.setEditable(false);

        tfError2.setEditable(false);

        tfError3.setEditable(false);

        tfError4.setEditable(false);

        buttonTodas.setText("Todas las preguntas");
        buttonTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTodasActionPerformed(evt);
            }
        });

        buttonPanelRapido.setText("Ver Panel Rápido");
        buttonPanelRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanelRapidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Segundo renglón para panel de una sola palabra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bNueva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(tfPista, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfPanel3)
                            .addComponent(tfPanel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfPanel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPanel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tfError1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonTodas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonPanelAzar, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfError4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfError3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfError2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonPanelRapido, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPanelAzar)
                    .addComponent(tfError1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfError2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPanelRapido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfError3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfError4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(tfPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNueva)
                    .addComponent(buttonTodas))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void cargar(){
        try{
            FileInputStream archivoEntrada = new FileInputStream("Datos Ruleta.dat");//Se crea un nuevo archivo de entrada, será 'Datos Parking.dat'
            ObjectInputStream oisArchivo = new ObjectInputStream(archivoEntrada);//Así se podrán almacenar datos.
            ruleta = (Programa) oisArchivo.readObject();/*Se hace un cast para almacenar en nuestro atributo 'aparcamiento'
            los datos que escribimos al cerrar el programa.
            */
            
        }catch(IOException ioe){/*Se capturarán diferentes excepciones. Si se inicia por primera vez el programa saltará una
            excepción diciendo que no encuentra el archivo, las demás veces no.*/
            System.out.println("Excepcion en cargar(): "+ioe.getMessage());
        }catch(ClassNotFoundException cnfe){
            System.out.println("Excepcion en cargar(): "+cnfe.getMessage());
        }catch(Exception e){
            System.out.println("Excepcion en cargar(): "+e.getMessage());
        }
    }
    /**El método guardar() servirá para salvar los datos que tengamos cuando cerremos el programa.
     */
    public static void guardar(){
        try{
            FileOutputStream archivoSalida = new FileOutputStream("Datos Ruleta.dat");/*Se crea el archivo donde se almacenarán
            los datos.*/
            ObjectOutputStream oosArchivo = new ObjectOutputStream(archivoSalida);
            Programa nuevo = ruleta;
            oosArchivo.writeObject(nuevo);
            archivoSalida.close();//Se cierra el archivo de salida.
            
        }catch (IOException ioe){//Se capturarán posibles excepciones.
            System.out.println("Excepcion en guardar() ioe: "+ioe.getMessage());
        }catch (Exception e){
            System.out.println("Excepcion en guardar(): "+e.getMessage());
        }
    }
    
    private void bNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevaActionPerformed
        try{
            boolean valido[] = new boolean[4];
            for(int i=0; i<4; i++){
                valido[i] = false;
            }
            if(tfPista.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No pueden estar la pista vacía.", "Fallo en el panel.", JOptionPane.ERROR_MESSAGE);
                throw new Exception ("No pueden estar la pista vacía.");
            }
            if(tfPanel1.getText().isEmpty() && tfPanel2.getText().isEmpty() && tfPanel3.getText().isEmpty() && tfPanel4.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No pueden estar todos los paneles vacíos.", "Fallo en el panel.", JOptionPane.ERROR_MESSAGE);
                throw new Exception ("No pueden estar todos los paneles vacíos.");
            }
            if(tfPanel1.getText().isEmpty()){
                tfPanel1.setText(" ");
            }
            if(tfPanel2.getText().isEmpty()){
                tfPanel2.setText(" ");
            }
            if(tfPanel3.getText().isEmpty()){
                tfPanel3.setText(" ");
            }
            if(tfPanel4.getText().isEmpty()){
                tfPanel4.setText(" ");
            }
            
            if(tfPanel1.getText().toString().length() > 12){
                tfError1.setBackground(Color.red);
                tfError1.setForeground(Color.white);
                tfError1.setText(""+(12-tfPanel1.getText().length()));
            }else{
                valido[0] = true;
                tfError1.setBackground(Color.green);
                tfError1.setForeground(Color.black);
                tfError1.setText("OK");
            }
            
            if(tfPanel2.getText().toString().length() > 14){
                tfError2.setBackground(Color.red);
                tfError2.setForeground(Color.white);
                tfError2.setText(""+(14-tfPanel2.getText().length()));
            }else{
                valido[1] = true;
                tfError2.setBackground(Color.green);
                tfError2.setForeground(Color.black);
                tfError2.setText("OK");
            }
            
            if(tfPanel3.getText().toString().length() > 14){
                tfError3.setBackground(Color.red);
                tfError3.setForeground(Color.white);
                tfError3.setText(""+(14-tfPanel3.getText().length()));
            }else{
                valido[2] = true;
                tfError3.setBackground(Color.green);
                tfError3.setForeground(Color.black);
                tfError3.setText("OK");
            }
            
            if(tfPanel4.getText().toString().length() > 12){
                tfError4.setBackground(Color.red);
                tfError4.setForeground(Color.white);
                tfError4.setText(""+(14-tfPanel4.getText().length()));
            }else{
                valido[3] = true;
                tfError4.setBackground(Color.green);
                tfError4.setForeground(Color.black);
                tfError4.setText("OK");
            }
            
            if(valido[0] && valido[1] && valido[2] && valido[3]){
                String panel1 = tfPanel1.getText();
                String panel2 = tfPanel2.getText();
                String panel3 = tfPanel3.getText();
                String panel4 = tfPanel4.getText();
                String pista = tfPista.getText();
                tfPanel1.setText("");
                tfPanel2.setText("");
                tfPanel3.setText("");
                tfPanel4.setText("");
                tfPista.setText("");
                ruleta.nuevaPregunta(panel1, panel2, panel3, panel4, pista);
                guardar();
                JOptionPane.showMessageDialog(null, "Panel añadido con éxito.", "Pregunta añadida.", WIDTH);
            }else{
                JOptionPane.showMessageDialog(null, "Los paneles 1 y 4 deben tener como mucho 12 caracteres y los 2 y 3 como mucho 14.", "Fallo en el panel.", JOptionPane.ERROR_MESSAGE);
                throw new Exception ("Los paneles 1 y 4 deben tener como mucho 12 caracteres y los 2 y 3 como mucho 14.");
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bNuevaActionPerformed

    private void buttonPanelAzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanelAzarActionPerformed
        try{
            VPanel vp = new VPanel();
            vp.pregunta = ruleta.seleccionar();
            if(vp.pregunta == null){
                JOptionPane.showMessageDialog(null, "Ya han salido todas las preguntas.", "Fallo en el panel.", JOptionPane.ERROR_MESSAGE);
                throw new Exception ("Ya han salido todas las preguntas.");
            }
            vp.cambiaPanel();
            vp.setVisible(true);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buttonPanelAzarActionPerformed

    private void buttonTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTodasActionPerformed
        if(!ruleta.baseDatos.isEmpty()){
            VPreguntas vp = new VPreguntas();
            vp.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "No hay preguntas en la base de datos", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonTodasActionPerformed

    private void buttonPanelRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanelRapidoActionPerformed
        try{
            VPanel vp = new VPanel();
            vp.pregunta = ruleta.seleccionar();
            if(vp.pregunta == null){
                JOptionPane.showMessageDialog(null, "Ya han salido todas las preguntas.", "Fallo en el panel.", JOptionPane.ERROR_MESSAGE);
                throw new Exception ("Ya han salido todas las preguntas.");
            }
            vp.rapida = true;
            vp.cambiaPanel();
            vp.setVisible(true);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buttonPanelRapidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bNueva;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonPanelAzar;
    private javax.swing.JButton buttonPanelRapido;
    private javax.swing.JButton buttonTodas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfError1;
    private javax.swing.JTextField tfError2;
    private javax.swing.JTextField tfError3;
    private javax.swing.JTextField tfError4;
    private javax.swing.JTextField tfPanel1;
    private javax.swing.JTextField tfPanel2;
    private javax.swing.JTextField tfPanel3;
    private javax.swing.JTextField tfPanel4;
    private javax.swing.JTextField tfPista;
    // End of variables declaration//GEN-END:variables
}
